"""empty message

Revision ID: 1c4cea75d66d
Revises: cd9abee9521a
Create Date: 2023-04-17 21:37:01.375386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4cea75d66d'
down_revision = 'cd9abee9521a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('counts', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('term', sa.String(length=50), nullable=False))
        batch_op.drop_column('table')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('term')
        batch_op.drop_column('counts')
        batch_op.drop_column('skills')

    # ### end Alembic commands ###
