"""empty message

Revision ID: 49fa2759e2fa
Revises: 1c4cea75d66d
Create Date: 2023-04-18 13:26:16.975082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49fa2759e2fa'
down_revision = '1c4cea75d66d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_table', schema=None) as batch_op:
        batch_op.alter_column('term',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               nullable=True)
        batch_op.create_foreign_key(None, 'search_term', ['term'], ['term'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('term',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
