"""empty message

Revision ID: cd9abee9521a
Revises: 3593bf309e39
Create Date: 2023-04-17 21:17:06.138218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9abee9521a'
down_revision = '3593bf309e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tech_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tech_table')
    # ### end Alembic commands ###
